Correccion forms
ndifabio92/ProyectoFinal-DigitalHouse pull request #37
Opened 2023-11-01 17:42 UTC by celu32

Todavia hay que mejorarle cosas pero voy a hacer el pull request para que puedan ir viendo el tema de las imagenes y agregandoselo. y de paso si pueden le hacen lo que falta que seria lo siguiente: 

1- cambiar los fetch que hice directamente por el useFetch  y los endpoints ingresados a mano por las funciones (no lo pude hacer funcionar de esa manera por eso lo deje funcionando asi)
2- hacer que luego de que se agregue un club o que se elimine un club, se vuelva a renderizar el listado actualizado.

2023-11-01 17:58 UTC, ndifabio92 requested changes
Encontre los siguientes temas
- El input de telefono acepta letras
![image](https://github.com/ndifabio92/ProyectoFinal-DigitalHouse/assets/51407236/ac505e0a-16ee-44a9-88b1-e32d3f8c4eba)
- No esta mostrando el nombre de la ciudad cuando se selecciona
![image](https://github.com/ndifabio92/ProyectoFinal-DigitalHouse/assets/51407236/b3130f3e-0b19-4f21-85be-83540077d771)


Otro punto no se si a todos les pasa, cuando hacen click al boton "Crear produto" y no hay ninguna campo seleccionado pasa lo siguiente
![image](https://github.com/ndifabio92/ProyectoFinal-DigitalHouse/assets/51407236/36f1b39f-5653-49fe-84a9-09f6fe8d2074)

2023-11-01 18:12 UTC, celu32 commented
Gracias Nico! 
el telefono esta puesto como string desde el back... si quieren que lo cambie a number deberian cambiarlo primero desde el back. 
Lo de la ciudad lo intente corregir pero no pude. entiendo que cuando desmockiemos las ciudades que estan mockeadas lo podemos corregir (A mi me gano...)
lo tercero no entendi pero lo podemos ver el juves en clase y me muestran.

2023-11-01 18:21 UTC, ndifabio92 commented
> Gracias Nico! el telefono esta puesto como string desde el back... si quieren que lo cambie a number deberian cambiarlo primero desde el back. Lo de la ciudad lo intente corregir pero no pude. entiendo que cuando desmockiemos las ciudades que estan mockeadas lo podemos corregir (A mi me gano...) lo tercero no entendi pero lo podemos ver el juves en clase y me muestran.

oka el ultimo es el mas importante, si le das al boton sin completar nada en el form, genera la pantalla blanca y falla la app, en vez de mostrarte las validaciones de los campos que estan vacios, por lo menos es lo que me pasa a mi.

2023-11-01 18:36 UTC, celu32 commented
ok, lo investigo y lo corrijo entonces

2023-11-02 04:20 UTC, celu32 commented
Ya se corrigieron los errores mencionados

2023-11-02 09:41 UTC, Valentinibar approved these changes

2023-11-02 12:52 UTC, merged