Characteristics clubes
ndifabio92/ProyectoFinal-DigitalHouse pull request #52
Opened 2023-11-10 14:53 UTC by sofiarodr

Add Characteristics Clubes

2023-11-10 16:21 UTC, ndifabio92 requested changes
Sofi falta agregar la relacion entre las de club y characteristics. 1 club puede tener muchas characteristics, vas a tener que modificar el dto de club para que soporte eso y el modelo para crear la relacion.
tambien despues vas a tener que modificar el update del club por que es este quien modifica sus characteristics asociadas.

2023-11-10 16:21 UTC, ndifabio92 commented on Back-End/canchas365/src/main/java/com/dh/canchas365/controller/CharacteristicsController.java
> +@RequestMapping("/CharacteristicsClubes")
Cambiar el nombre a characteristics, los endopint van en miniscula y si son 2 palabras van en camelcase.
Aca solo seria characteristics porque es el crud de general

2023-11-10 16:21 UTC, ndifabio92 commented on Back-End/canchas365/src/main/java/com/dh/canchas365/controller/CharacteristicsController.java
> +    private CharacteristicsController service;
Tenes que llamar al CharacteristicsService, no al controller

2023-11-10 16:21 UTC, ndifabio92 commented on Back-End/canchas365/src/main/java/com/dh/canchas365/controller/CharacteristicsController.java
> +            Optional<Category> optional = service.findById(id);
esto no tendria que devolver una Category, tendria que devolver un Characteristics

2023-11-10 16:21 UTC, ndifabio92 commented on Back-End/canchas365/src/main/java/com/dh/canchas365/controller/CharacteristicsController.java
> +                return ResponseEntity.status(HttpStatus.OK).body(service.update(category,id));
solo tenes que enviar characteristics para el update

2023-11-10 16:21 UTC, ndifabio92 commented on Back-End/canchas365/src/main/java/com/dh/canchas365/dto/CharacteristicsClubesDto.java
> +public class CharacteristicsClubesDto {
Lo mismo con el nombre solo seria CharacteristicsDto

2023-11-10 16:21 UTC, ndifabio92 commented on Back-End/canchas365/src/main/java/com/dh/canchas365/dto/CharacteristicsClubesDto.java
> +    private string id;
los Id son Long

2023-11-10 16:21 UTC, ndifabio92 commented on Back-End/canchas365/src/main/java/com/dh/canchas365/model/CharacteristicsClubes.java
> +@Table(name = "CharacteristicsClubes")
Los mismo con el nombre Characteristics, igual no hace falta definir el nombre de la tabla si es igual al nombre del entity/model

2023-11-10 16:21 UTC, ndifabio92 commented on Back-End/canchas365/src/main/java/com/dh/canchas365/model/CharacteristicsClubes.java
> +    private String id;
Los Id son Long

2023-11-10 16:21 UTC, ndifabio92 commented on Back-End/canchas365/src/main/java/com/dh/canchas365/model/CharacteristicsClubes.java
> +    public CharacteristicsClubes(String id, String name, String url) {
arriba de todos tenes @NoArgsConstructor, no hace falta crear un constructor

2023-11-10 16:21 UTC, ndifabio92 commented on Back-End/canchas365/src/main/java/com/dh/canchas365/model/CharacteristicsClubes.java
Te faltan las anotaciones @Column y las validaciones como esta en category

2023-11-10 16:21 UTC, ndifabio92 commented on Back-End/canchas365/src/main/java/com/dh/canchas365/service/CharacteristicsClubesService.java
> +public class CharacteristicsClubesService extends CustomFieldException {
el nombre seria CharacteristicsService

2023-11-10 16:21 UTC, ndifabio92 commented on Back-End/canchas365/src/main/java/com/dh/canchas365/service/CharacteristicsClubesService.java
> +    private ClubRepository clubRepository;
No tendrias que estar llamando al Club

2023-11-10 16:21 UTC, ndifabio92 commented on Back-End/canchas365/src/main/java/com/dh/canchas365/service/CharacteristicsClubesService.java
> +    public Characteristics update(Characteristics characteristics, String id){
no esta creada la relacion entre club y characteristics, igual esa actualizacion no iria aca, aca solo se actualiza la characteristics

2023-11-10 16:21 UTC, ndifabio92 commented on Back-End/canchas365/src/main/java/com/dh/canchas365/service/CharacteristicsClubesService.java
> +    public Characteristics update(Characteristics characteristics, String id){
Los Id siempre son Long

2023-11-10 16:21 UTC, ndifabio92 commented on Back-End/canchas365/src/main/java/com/dh/canchas365/service/CharacteristicsClubesService.java
Faltaria un metodo que se llama finByid para que devuelva una Characteristics por id

2023-11-10 16:32 UTC, saciar-dev commented on Back-End/canchas365/src/main/java/com/dh/canchas365/model/CharacteristicsClubes.java
> +    public CharacteristicsClubes(String id, String name, String url) {
ojo! @NoArgsConstructor define un constructor sin argumentos, para lograr ese constructor tenes que agregar @AllArgsConstructor

2023-11-10 16:36 UTC, saciar-dev commented on Back-End/canchas365/src/main/java/com/dh/canchas365/service/CharacteristicsClubesService.java
a JpaRepository hay q pasarle el tipo de dato del id (que deberia ser Long cuando se cambie en el model)

2023-11-11 15:01 UTC, celu32 requested changes

2023-11-11 15:02 UTC, celu32 requested changes

2023-11-11 15:02 UTC, celu32 commented on Back-End/.idea/misc.xml
hola sofi, podrias explicar  por que has cambiado esta version?

2023-11-11 15:04 UTC, celu32 commented on Back-End/canchas365/src/main/java/com/dh/canchas365/model/Club.java
la relacion es uno a muchos, deberia ser un hash o un arraylist de caracteristicas

2023-11-11 23:13 UTC, closed without merging